### ISSUE TITLE
Python 3.4 support not working

### ISSUE THREAD

**Issue by d3prof3t** [ozgur/python-linkedin#86]
Hi @ozgur 
I know this issue has been addresses previously in some other issue id. But I somehow am not able to make this work.
I am working on a virtualenvwrapper which is having python 3.4.2

When I run the http_api.py; I get the following output:

Traceback (most recent call last):
  File "http_api.py", line 1, in <module>
    from linkedin import linkedin
  File "/home/Saurabh/.virtualenvs/jobfinder/lib/python3.4/site-packages/linkedin/linkedin.py", line 294
    except (requests.ConnectionError, requests.HTTPError), error:
                                                         ^
SyntaxError: invalid syntax

Please fix this issue as soon as possible, in need urgently.
Thanks

**Comment by d3prof3t** [comment]
Hi @ozgur 
Can u please share your email or any contact detail, I just need to contact you because I'm stuck in a project and I really need this suport to start working. Hope to hear a reponse from you soon.

**Comment by ldesgardin** [comment]
Hi there,

same issue for me. Is there a way to workaround according to you ?

Thanks and Regards,
Ludovic

**Comment by yiningz** [comment]
I get the same problems too. I have to manually revise the code. Any better ways?

**Comment by marshallhumble** [comment]
Hello All, I have moved this to https://github.com/marshallhumble/python-linkedin and am working on support, I am looking to support 3.4/3.5 only.  You can run the package from cloning this repo and running python setup.py install.  

Please report issues on that repo and hopefully we can get this up and maintained again.

**Comment by d3prof3t** [comment]
Thanks everyone!
